export const PLAN_NAMES = {
  STANDARD: "Standard",
  STANDARD_HALF_DAY: "Standard Half Day",
  STANDARD_HALF_DAY_ALL: "Standard Half Day All",
  HALF_DAY_ALL_INCLUSIVE: "Half Day All Inclusive",
  FULL_EXPERIENCE: "Full Experience",
  FULL_DAY_EXPERIENCE: "Full Day Experience",
  COMFORT_PLUS: "Comfort Plus",
  SUNSET_AND_BALLENA: "Sunset & Ballena",
} as const;

export const PLAN_GROUPS = {
  BASE_PLANS: [
    PLAN_NAMES.STANDARD,
    PLAN_NAMES.STANDARD_HALF_DAY,
    PLAN_NAMES.STANDARD_HALF_DAY_ALL,
    PLAN_NAMES.SUNSET_AND_BALLENA,
  ],
  PLUS_PLANS: [
    PLAN_NAMES.HALF_DAY_ALL_INCLUSIVE,
    PLAN_NAMES.FULL_EXPERIENCE,
    PLAN_NAMES.FULL_DAY_EXPERIENCE,
  ],
  PRO_PLANS: [PLAN_NAMES.COMFORT_PLUS],
  ALL: [
    PLAN_NAMES.STANDARD,
    PLAN_NAMES.STANDARD_HALF_DAY,
    PLAN_NAMES.HALF_DAY_ALL_INCLUSIVE,
    PLAN_NAMES.FULL_EXPERIENCE,
    PLAN_NAMES.FULL_DAY_EXPERIENCE,
    PLAN_NAMES.COMFORT_PLUS,
  ],
} as const;
