CREATE TYPE "public"."boat_type" AS ENUM('Viking', 'Superpanga', 'Sport Fisher', 'Sport Fishing Boat', 'Luxury Yacht');--> statement-breakpoint
ALTER TABLE "Amenities" DROP CONSTRAINT "Amenities_id_unique";--> statement-breakpoint
ALTER TABLE "Boat_Plan_Prices" DROP CONSTRAINT "Boat_Plan_Prices_id_unique";--> statement-breakpoint
ALTER TABLE "Boats" DROP CONSTRAINT "Boats_id_unique";--> statement-breakpoint
ALTER TABLE "Boats_Media" DROP CONSTRAINT "Boats_Media_id_unique";--> statement-breakpoint
ALTER TABLE "Services" DROP CONSTRAINT "Services_id_unique";--> statement-breakpoint
ALTER TABLE "Partners" DROP CONSTRAINT "Partners_id_unique";--> statement-breakpoint
ALTER TABLE "Plans" DROP CONSTRAINT "Plans_id_unique";--> statement-breakpoint
ALTER TABLE "Plan_Amenities" DROP CONSTRAINT "Plan_Amenities_id_unique";--> statement-breakpoint
ALTER TABLE "Locations" DROP CONSTRAINT "Locations_id_unique";--> statement-breakpoint
ALTER TABLE "Service_Time_Slots" DROP CONSTRAINT "Service_Time_Slots_id_unique";--> statement-breakpoint
ALTER TABLE "Reservations" DROP CONSTRAINT "Reservations_id_unique";--> statement-breakpoint
ALTER TABLE "Reservation_Items" DROP CONSTRAINT "Reservation_Items_id_unique";--> statement-breakpoint
ALTER TABLE "payments" DROP CONSTRAINT "payments_transaction_id_unique";--> statement-breakpoint
ALTER TABLE "payments" DROP CONSTRAINT "status_check";--> statement-breakpoint
ALTER TABLE "Boat_Plan_Prices" DROP CONSTRAINT "Boat_Plan_Prices_boat_id_Boats_id_fk";
--> statement-breakpoint
ALTER TABLE "Boat_Plan_Prices" DROP CONSTRAINT "Boat_Plan_Prices_plan_id_Plans_id_fk";
--> statement-breakpoint
ALTER TABLE "Boats" DROP CONSTRAINT "Boats_partner_id_Partners_id_fk";
--> statement-breakpoint
ALTER TABLE "Boats_Media" DROP CONSTRAINT "Boats_Media_boat_id_Boats_id_fk";
--> statement-breakpoint
ALTER TABLE "Plans" DROP CONSTRAINT "Plans_service_id_Services_id_fk";
--> statement-breakpoint
ALTER TABLE "Plan_Amenities" DROP CONSTRAINT "Plan_Amenities_boat_plan_price_id_Boat_Plan_Prices_id_fk";
--> statement-breakpoint
ALTER TABLE "Plan_Amenities" DROP CONSTRAINT "Plan_Amenities_amenity_id_Amenities_id_fk";
--> statement-breakpoint
ALTER TABLE "Location_Departures" DROP CONSTRAINT "Location_Departures_boat_id_Boats_id_fk";
--> statement-breakpoint
ALTER TABLE "Location_Departures" DROP CONSTRAINT "Location_Departures_location_id_Locations_id_fk";
--> statement-breakpoint
ALTER TABLE "Service_Time_Slots" DROP CONSTRAINT "Service_Time_Slots_service_id_Services_id_fk";
--> statement-breakpoint
ALTER TABLE "Reservation_Items" DROP CONSTRAINT "Reservation_Items_reservation_id_Reservations_id_fk";
--> statement-breakpoint
ALTER TABLE "Reservation_Items" DROP CONSTRAINT "Reservation_Items_boat_plan_price_id_Boat_Plan_Prices_id_fk";
--> statement-breakpoint
ALTER TABLE "Reservation_Items" DROP CONSTRAINT "Reservation_Items_service_time_slot_id_Service_Time_Slots_id_fk";
--> statement-breakpoint
ALTER TABLE "Reservation_Items" DROP CONSTRAINT "Reservation_Items_location_id_Locations_id_fk";
--> statement-breakpoint
ALTER TABLE "payments" DROP CONSTRAINT "payments_reservation_id_Reservations_id_fk";
--> statement-breakpoint
ALTER TABLE "Boats_Media" ALTER COLUMN "media_type" SET DATA TYPE text;--> statement-breakpoint
DROP TYPE "public"."media_type";--> statement-breakpoint
CREATE TYPE "public"."media_type" AS ENUM('video', 'image');--> statement-breakpoint
ALTER TABLE "Boats_Media" ALTER COLUMN "media_type" SET DATA TYPE "public"."media_type" USING "media_type"::"public"."media_type";--> statement-breakpoint
ALTER TABLE "Location_Departures" DROP CONSTRAINT "Location_Departures_boat_id_location_id_pk";--> statement-breakpoint
ALTER TABLE "Amenities" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Amenities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Amenities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Boat_Plan_Prices" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Boat_Plan_Prices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Boat_Plan_Prices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Boats" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Boats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Boats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Boats_Media" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Boats_Media" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Boats_Media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Services" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Services" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Services_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Partners" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Partners" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Partners_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Plans" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Plans" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Plans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Plan_Amenities" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Plan_Amenities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Plan_Amenities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Locations" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Locations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Service_Time_Slots" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Service_Time_Slots" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Service_Time_Slots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Reservations" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Reservations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Reservation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "Reservation_Items" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "Reservation_Items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "Reservation_Items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "transaction_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "status" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "amount" SET DATA TYPE numeric(10, 2);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "currency" SET DATA TYPE varchar(10);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "currency" SET DEFAULT 'USD';--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "payment_method" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "payments" ALTER COLUMN "payment_method" SET DEFAULT 'paypal';--> statement-breakpoint
ALTER TABLE "Location_Departures" ADD CONSTRAINT "Locations_Departures_pkey" PRIMARY KEY("boat_id","location_id");--> statement-breakpoint
ALTER TABLE "Boats" ADD COLUMN "is_popular" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "Boats" ADD COLUMN "type" "boat_type" DEFAULT 'Luxury Yacht' NOT NULL;--> statement-breakpoint
ALTER TABLE "Boat_Plan_Prices" ADD CONSTRAINT "Boat_Plan_Prices_boat_id_fkey" FOREIGN KEY ("boat_id") REFERENCES "public"."Boats"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Boat_Plan_Prices" ADD CONSTRAINT "Boat_Plan_Prices_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "public"."Plans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Boats" ADD CONSTRAINT "Boats_partner_id_fkey" FOREIGN KEY ("partner_id") REFERENCES "public"."Partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Boats_Media" ADD CONSTRAINT "Boats_Media_boat_id_fkey" FOREIGN KEY ("boat_id") REFERENCES "public"."Boats"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Plans" ADD CONSTRAINT "Plans_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "public"."Services"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Plan_Amenities" ADD CONSTRAINT "Plan_Amenities_amenities_id_fkey" FOREIGN KEY ("amenity_id") REFERENCES "public"."Amenities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Plan_Amenities" ADD CONSTRAINT "Plan_Amenities_boat_plan_price_id_fkey" FOREIGN KEY ("boat_plan_price_id") REFERENCES "public"."Boat_Plan_Prices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Location_Departures" ADD CONSTRAINT "Locations_Departures_boat_id_fkey" FOREIGN KEY ("boat_id") REFERENCES "public"."Boats"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Location_Departures" ADD CONSTRAINT "Locations_Departures_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."Locations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Service_Time_Slots" ADD CONSTRAINT "Service_Time_Slots_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "public"."Services"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Reservation_Items" ADD CONSTRAINT "Reservation_Items_boat_plan_price_id_fkey" FOREIGN KEY ("boat_plan_price_id") REFERENCES "public"."Boat_Plan_Prices"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Reservation_Items" ADD CONSTRAINT "Reservation_Items_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."Locations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Reservation_Items" ADD CONSTRAINT "Reservation_Items_reservation_id_fkey" FOREIGN KEY ("reservation_id") REFERENCES "public"."Reservations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "Reservation_Items" ADD CONSTRAINT "Reservation_Items_service_time_slot_id_fkey" FOREIGN KEY ("service_time_slot_id") REFERENCES "public"."Service_Time_Slots"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "fk_reservation" FOREIGN KEY ("reservation_id") REFERENCES "public"."Reservations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_reservation_pending" ON "Reservations" USING btree ("reservation_status" enum_ops);--> statement-breakpoint
ALTER TABLE "Amenities" ADD CONSTRAINT "Amenities_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Boat_Plan_Prices" ADD CONSTRAINT "Boat_Plan_Prices_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Boats" ADD CONSTRAINT "Boats_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Boats_Media" ADD CONSTRAINT "Boats_Media_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Services" ADD CONSTRAINT "Services_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Partners" ADD CONSTRAINT "Partners_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Plans" ADD CONSTRAINT "Plans_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Plan_Amenities" ADD CONSTRAINT "Plan_Amenities_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Service_Time_Slots" ADD CONSTRAINT "Service_Time_Slots_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Reservations" ADD CONSTRAINT "Reservation_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "Reservation_Items" ADD CONSTRAINT "Reservation_Items_id_key" UNIQUE("id");--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_transaction_id_key" UNIQUE("transaction_id");--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_status_check" CHECK ((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[]));